
# when leaving the console clear the screen to increase privacy
if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi

if [ "$DISPLAY" ];then
   cln -a $HOME
fi
# builtin cd; cleanup &
gnome-session-quit || true
