#! /bin/bash

# load common variables
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
export default_dir=${default_dir:=$HOME}
export default_bashdir=${default_bashdir:=$default_dir/etc/shells/bash}
if test -f $default_bashdir/bash_vars ; then
	. $default_bashdir/bash_vars;
fi

for file in $default_bashdir/bashrc.d/*; do
    case "$file" in
        *~|*.bak|*.old|*.sw?|*.zwc|*.disabled) continue;;
    esac
    source $file
done

## trap: trap [arg] [signal_spec]
##    The command ARG is to be read and executed when the shell receives
##    signal(s) SIGNAL_SPEC.  If ARG is absent all specified signals are
##    reset to their original values.  If ARG is the null string this
##    signal is ignored by the shell and by the commands it invokes.  If
##    SIGNAL_SPEC is EXIT (0) the command ARG is executed on exit from
##    the shell.  The trap command with no arguments prints the list of
##    commands associated with each signal number.  SIGNAL_SPEC is either
##    a signal name in <signal.h>, or a signal number.  The syntax `trap -l'
##    prints a list of signal names and their corresponding numbers.
##    Note that a signal can be sent to the shell with "kill -signal $$".
## trap -l
##  0) EXIT         1) SIGHUP       2) SIGINT       3) SIGQUIT
##  4) SIGILL       5) SIGTRAP      6) SIGIOT       7) SIGEMT
##  8) SIGFPE       9) SIGKILL     10) SIGBUS      11) SIGSEGV
## 12) SIGSYS      13) SIGPIPE     14) SIGALRM     15) SIGTERM
## 16) SIGURG      17) SIGSTOP     18) SIGTSTP     19) SIGCONT
## 20) SIGCHLD     21) SIGTTIN     22) SIGTTOU     23) SIGIO
## 24) SIGXCPU     25) SIGXFSZ     26) SIGVTALRM   27) SIGPROF
## 28) SIGWINCH    29) SIGLOST     30) SIGUSR1     31) SIGUSR2



# Local Variables: 
# comment-start: "#" 
# tab-width: 2 
# mode: sh
# End: 

